### ISSUE TITLE
upgrade to elm 0.17

### ISSUE THREAD

**Issue by despairblue** [splodingsocks/elm-starter#4]
Seems fairly straight forward except for `grunt-elm`, right?

Although, after seeing [your video](https://egghead.io/lessons/elm-build-a-tiny-app-using-the-standard-elm-architecture), it probably should look something like [this](https://github.com/despairblue/elm-starter)
right?

**Comment by mrmurphy** [comment]
Thanks for the reminder, and the example, @despairblue! I'd just pushed up a revised and updated version.

**Comment by despairblue** [comment]
@splodingsocks 👍  but I think the elm dependency is missing.

**Comment by mrmurphy** [comment]
You're right. I'll get that fixed. Thanks!
